sudo: false

language: php

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest TEST_PACKAGE=all
    - php: 5.6
      env: WP_VERSION=latest TEST_PHAR=nightly
    - php: 5.6
      env: WP_VERSION=latest TEST_PHAR=stable
  allow_failures:
    - php: 5.6
      env: WP_VERSION=latest TEST_PHAR=stable

before_script:
  - ./ci/prepare.sh

script: ./ci/test.sh

after_success: ./ci/deploy.sh

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      secure: fJh4UF4zBB/qKZkh2Jt1CY9D/OxliEW1lAH0/PESSDPMFBUEBHEA60feaGNxVG5MWnErZxAirT+mT9ZCvCIHb2gekaRTODcCuOohq4xI5duSNedf/ZVf6rYPr6GNqgiwDP7xjodNCmCIXPjh7WQSICFqsNb0t17mar85iEulbkvj5GflimCypWY/2iIWNzbWziInQzfBKZvcBOjAopO/ZHBa5Xv4FGJWmwkRks9Sn9vMWIxMn0Vhl3YM1/5kkUFtS/FhT+zXy9sg62qL9ACdg9XPcfVCFgSNhRMsFmEM0nzrJsVL7hpbQfo8niA6eASQZJfV0cmNTa7lewuSlUffvUQU6sMK+qtmjocJWHcBaba0Ph2Y8WM1Q8W3tY0Nl+DlTIFblS62rmxMkRxKEjHaP3hI8ISGzfwDnNU6IKn6XdT3k/ZdrZrKV6HL8fo+qMgbpeOnGwgZSDUeT1LgMaNEoRfpqc/z7IGLnRF9+vHbwvAN5H+Mfw5iKJMFjBxn8Xf8XARJh1e9fmZKZ8+HDQoLTbSznN0mbn2Vn0PjKN9mdKUFDVSXEBjhYsfnj6mUdxT3pxtah6mnTuR+pgoSDesu/hQP/30L6MZPbS8Ia4hEtl2jLnkJZLABsEmdeGBCkQozrE7S1DHyelhxAppdONBvipM2jOFu/kEFCl6ImWVz8l8=
