sudo: false

language: php

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest TEST_PACKAGE=all
    - php: 5.6
      env: WP_VERSION=latest TEST_PHAR=nightly
    - php: 5.6
      env: WP_VERSION=latest TEST_PHAR=stable
  allow_failures:
    - php: 5.6
      env: WP_VERSION=latest TEST_PHAR=stable

before_script:
  - ./ci/prepare.sh

script: ./ci/test.sh

after_success: ./ci/deploy.sh

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      secure: LuDOP1T+HXg6E4+ijpSY0YuUH9cwPUp4V9emq2rXJ+oQ2i6zMA5bTufF/d6MqmzVhYrYKaiqII1DyMheTzn7ulZlTjbAsG0ADlbtBzovrMhlRE1mV4e+CmJJHXVMyDI7Q9vkfqILng+PKrERY+OypHbe9DmgQQ2C295aJq0eogxFpGWtGCDl1R5kfJJBfKwdAbmwTjnJFStNjUFTuJ6efZTy8kPam2UbYmiIAAXmMhKtz4rva4cA1DO7gEU64ldp27OZGMAASM/2n9z0BYP1ecQJIxykG3jUYwShZ3vq86E8TuHpdZNhU0w8dpx96q9XnhiY4mbruIjVGA9qWjm0fiacLjzlPfnFT4V3p4P/KdHXXAQoUQNlqNx7ydOKeTqzOMhlydMSix/NxYLM45eLfL+CsU1HJyZSBO88M4j9AHVr8yYuHAzWGpYvuT4JjddTkjxnm1jFAzBIgMkADxr/F/LzluOuhBHWHNxbbFtciOFFg4q7ave6Yob+kGYAf7KmiUzYGwOgGZUgltVgF4NLwvYuEaK3gai7ZIJhuLUGkkNJkZuW3gOJQiMOW9J9v8rOVWgtry/LsGeLyam3JaI2COKGxVMY/iz49jxxnhrVH9wUTVL39Cn24FK33h9T114ZYoxyj6AIeJedCWGkdHrxinkoJDZ002+ewI8aVoYJvvA=
