sudo: false

language: php

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest TEST_PACKAGE=wp-cli/wp-cli
    - php: 5.6
      env: WP_VERSION=latest TEST_PACKAGE=commands

before_script:
  - ./ci/prepare.sh

script: ./ci/test.sh

after_success: ./ci/deploy.sh

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
